services:
  database:
    image: mariadb:11.6
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  media:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/media:/app/media
    ports:
      - "80:80"