# Generated by Django 5.1.4 on 2024-12-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/images/profile/"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_alt",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_src",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.profileavatar",
            ),
        ),
    ]
