# Generated by Django 5.1.4 on 2024-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
