# Generated by Django 5.1.4 on 2024-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="images",
        ),
    ]
