# Generated by Django 5.1.4 on 2024-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_image_product_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
