# Generated by Django 5.1.4 on 2024-12-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_sale_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="free_delivery",
            new_name="freeDelivery",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="full_description",
            new_name="fullDescription",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="date_from",
            new_name="dateFrom",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="date_to",
            new_name="dateTo",
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="sale_price",
            new_name="salePrice",
        ),
    ]
