# Generated by Django 5.1.4 on 2024-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_free_delivery_product_freedelivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(upload_to="media/images/products/"),
        ),
    ]
